# Generated by Django 3.2.6 on 2021-12-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('US', 'Used'), ('NE', 'New')], default='US', max_length=2),
        ),
    ]
